### ISSUE TITLE
must use RAM 41K，can not save some？

### ISSUE THREAD

**Issue by xianyo** [bitbank2/unzipLIB#14]
must use RAM 41K，can not save some？

maybe can 32K to 16K？

change MAX_WBITS or other。。

**Comment by bitbank2** [comment]
FLATE by default uses a 32K sliding window for best compression. The compressor can choose to use a smaller window and then the decompressor will require less RAM. If you want to be able to decode any ZIP file, then you need to allocate sufficient memory. I could allocate the memory dynamically, but the reason I did it this way is for very simple embedded targets with no malloc/free functionality. You're free to change it as you wish for your needs.
