### ISSUE TITLE
SdFat example

### ISSUE THREAD

**Issue by samsmith94** [bitbank2/unzipLIB#2]
Hello,
I would have a question.
Do you have some example code for SdFat library (https://github.com/greiman/SdFat)?
I would like to use your library, but on STM32, I can't use the standard SD library.

**Comment by bitbank2** [comment]
The callback functions for file access are quite simple. You would just need to call the open/read/close of SDfat from the callback functions of the same name. Start from the SD lib example and make the needed changes.
